trade-tariff/trade-tariff-tools

- .github/pull_request_template.md
- .github/workflows/release_notes.yml
- .gitignore
- bin/generate_release_notes.sh
- bin/post_release_notes.sh
https://transformuk.atlassian.net/browse/HOTT-2650
- This makes significant improvements on the manual release note process and means developers can be on holiday, etc, and the relevant stakeholders still receive the right information about what is going into a given release
- The releases are not continuous right now and happen on preselected days of the week (Monday and Thursday)
> HOTT-2650: Automates release note generation

- bin/generate_release_notes.sh
HOTT-<TODO>
This change produces a cache file containing the following:
```
william.michael.fish@gmail.com|<https://github.com/willfish|willfish>
maverickvi@users.noreply.github.com|maverickvi@users.noreply.github.com
jeb@jdwilkins.co.uk|jeb@jdwilkins.co.uk
```
- This solves issues where we're being rate limited by the github api and spamming to fetch usernames for lots of merge commits
> Store resolved github author in a cache

- bin/generate_release_notes.sh
HOTT-<TODO>
- Between Thursday and Monday we'll lose visiblity on what got released for these repos
> Move to 5 days for release note history

- bin/post_release_notes.sh
HOTT-<TODO>
- This wasn't required previously but we're receiving invalid_payload messages in the github action output
> Escape release-note json payload to slack

- .github/workflows/release_notes.yml
- bin/generate_release_notes.sh
BAU
- Adds tech-docs to release notes
- Uses GITHUB_TOKEN provided by Github Actions
- Provide more visibility around tech docs
> BAU: Adds tech-docs to release notes

- .github/pull_request_template.md
- bin/generate_release_notes.sh
BAU
- Adds visibility for the tech docs repo
- Fix dead reference to an older jira board
- For visibility
> BAU: Provide visibility over the tech-docs

- bin/generate_release_notes.sh
BAU
- I had this confused with signon which only deploys to development and staging environments
> BAU: Fixes admin release type

- .github/actions/fetch-secrets/action.yml
- Altered jq expression to escape parentheses for correct key-value formatting
- The unquoted parentheses in the jq expression were being misinterpreted by the shell, leading to errors.
- By adding the escape characters, the jq expression now formats key-value pairs correctly when writing them to the .env file.
> Correct fetch secret script

- bin/generate-release-notes
BAU
- We've migrated to CD in the frontend now so there are very few apps (just the backend and terraform) that rollout manually
> BAU: Leave only manually deployed stuff in release notes

- .github/actions/terraform-apply/action.yml
BAU
- This should prevent us from instantly failing due to an inability to acquire the lock with successive merges
> BAU: Allow for up to 2 deployments to happen in order

- .github/workflows/e2e-fpo-tests.yml
- .github/workflows/e2e-tests.yml
This is going to be called by the fpo/dev-hub repositories
[HMRC-896](https://transformuk.atlassian.net/browse/HMRC-896)
- This is needed to migrate the fpo lambda repo to github actions
> HMRC-896: Adds workflow for e2e-fpo-tests

- bin/generate-release-notes
BAU
- We've moved to Continuous Deployments of the backend repo
> BAU: Removes all but last of release note repos

- .github/actions/slack-notify/action.yml
[HMRC-962](https://transformuk.atlassian.net/browse/HMRC-962)
- We should be able to notify different channels depends on the environment
> HMRC-962: Notify in production-alerts

- .github/actions/setup-terraform-docs/action.yml
[HMRC-903](https://transformuk.atlassian.net/browse/HMRC-903)
- This is needed for easy installation of terraform docs
> HMRC-903: Adds terraform docs action

- .github/actions/lock-docker-compose/action.yml
HMRC
- Preevy currently fails with newer versions of Docker Compose due to the deprecation of the docker-compose subcommand.
- This patch ensures stability until Preevy’s codebase is updated to support newer Docker Compose versions.
> Lock Docker Compose to v2.36.0 to prevent preevy from failing

- .github/workflows/stop-development-services.yml
[HMRC-1306](https://transformuk.atlassian.net/browse/HMRC-1306)
- This is necessary to cut costs and leave development in a mostly on-demand/dormant state
> HMRC-1306: Adds a workflow to stop all services in development

- .github/actions/build-and-push/action.yml
- .github/actions/tag-production/action.yml
- .github/actions/terraform-apply/action.yml
- .github/actions/terraform-plan/action.yml
- .github/workflows/deploy-ecs.yml
[HMRC-1380](https://transformuk.atlassian.net/browse/HMRC-1380)
- This will enable configurable matrices of multi-app deployments with e2e tests
> HMRC-1380: Support repo and ref as inputs to ecs deployment workflow

- .github/workflows/e2e-tests.yml
[HMRC-1441](https://transformuk.atlassian.net/browse/HMRC-1441)
- This is needed to make sure we're able to run the passwordless verification tests and catch out any failures
> HMRC-1441: Adds context and role assumption for passwordless verification

- .github/workflows/e2e-tests.yml
BAU
- These are a bit intermittent and I want the dust to settle while I'm off https://github.com/trade-tariff/trade-tariff-e2e-tests/pull/38
> BAU: Default to skipping passwordless verification

- .github/workflows/preview-cleanup.yml
BAU
- We want Slack notifications to only send a message when environments were actually deleted
- Now only checks PRs in the repository that matches the environment (admin envs only check trade-tariff-admin PRs).
> BAU: Limit slack notification

- .github/actions/build-and-push/action.yml
[HMRC-1170](https://transformuk.atlassian.net/browse/HMRC-1170)
- This ensures Docker automatically retrieves short-lived credentials when building and pushing images.
- Improves security by avoiding plaintext passwords in workflows.
- Reduces boilerplate: no need to run `docker login` explicitly.
> HMRC-1170: Switch to Amazon ECR credential helper in build-and-push action

- bin/ecs
[HMRC-1604](https://transformuk.atlassian.net/browse/HMRC-1604)
- This is needed to make sure we can run arbitrary tasks on the `backend-job` container in production (I needed it for restoring the database)
> HMRC-1604: bin/ecs fixes
