trade-tariff/trade-tariff-tools

bin/generate_release_notes.sh

https://transformuk.atlassian.net/browse/HOTT-2660
- This makes it easier to know who merged the code change

HOTT-2660: Adds merge commit author information to release notes

---

bin/generate_release_notes.sh

https://transformuk.atlassian.net/browse/HOTT-2682
- This will help with visiblity of customer-facing changes

HOTT-2682: Support api docs in release notes workflow

---

.github/workflows/release_notes.yml
bin/generate_release_notes.sh

https://transformuk.atlassian.net/browse/HOTT-2683
- This helps with visibility/early discovery of issues

HOTT-2683: Adds approval and build status to release notes

---

bin/generate_release_notes.sh

https://transformuk.atlassian.net/browse/HOTT-3198
- This is used by people and should be visible

HOTT-3139: Adds reporting repo to release notes

---

bin/generate_release_notes.sh

BAU
- We actively develop this repo

BAU: Adds trade-tariff-platform-aws-terraform to release notes

---

.github/workflows/release_notes.yml
bin/fetch-deployers
bin/generate_release_notes.sh

BAU
- This enables us to make sure that a random primary and secondary deployer is mentioned in the release notes for a given day

BAU: Adds deployers to release notes

---

bin/generate_release_notes.sh

BAU
- Just for extra visibility

BAU: Adds FPO project to release notes

---

bin/generate_release_notes.sh

Reverts trade-tariff/trade-tariff-tools#14

Revert "BAU: Adds FPO project to release notes"

---

bin/generate_release_notes.sh

BAU: Debug

---

bin/generate_release_notes.sh

BAU
- This is required to make sure we've got visibility on what needs to be released to FPO search production

BAU: Adds FPO search to release notes

---

bin/generate_release_notes.sh

BAU
Use PAT to enable private clones

BAU: Fix private release notes

---

.github/workflows/release_notes.yml
bin/generate_release_notes.sh

Reverts trade-tariff/trade-tariff-tools#22

Revert "BAU: Adds tech-docs to release notes"

---

bin/generate_release_notes.sh

FPO-209: Adds fpo e2e tests repo for visibility

---

bin/generate_release_notes.sh
bin/post_release_notes.sh

FPO-278
- This app is now continuously deployed and the batch release doesn't make sense

FPO-278: Migrate fpo search notes to being merge commits in days oriented

---

bin/generate_release_notes.sh

BAU
- Just for some visibility on these changes

BAU: Adds replication repo to notes

---

bin/generate_release_notes.sh

BAU: Adds commodi-tea

---

bin/generate_release_notes.sh

BAU
- This should make it clearer to a deployer what the relase type is and what actions are needed

BAU: Be more accurate about what kind of release is happening

---

.github/workflows/e2e-fpo-tests.yml
.github/workflows/e2e-tests.yml

[HMRC-1061](https://transformuk.atlassian.net/browse/HMRC-1061)
- This is working during a push workflow invocation in the caller but not in the dispatch workflow

HMRC-1061: Simplify the e2e workflow

---

.github/actions/terraform-apply/action.yml
.github/actions/terraform-plan/action.yml
CODEOWNERS

BAU: Bumps terraform

---

.github/workflows/preview-cleanup.yml

HMRC
- Maintenance overhead (updates need to be applied in multiple places).

BAU: Add preview-cleanup workflow

---

.github/actions/terraform-plan/action.yml

BAU
- Plans were moved to acquiring locks and not just mutating applies

BAU: Plans now acquire locks and this is causing lots of acquire lock failures

---

.github/workflows/deploy-ecs.yml
.github/workflows/deploy-multi-ecs.yml
.github/workflows/e2e-fpo-tests.yml

[PRDEX-229](https://transformuk.atlassian.net/browse/PRDEX-229)
- This is required to migrate to passwordless

PRDEX-229: Assume role in FPO tests
